### ISSUE TITLE
dot_model_checkpoints.zip file is corrupted

### ISSUE THREAD

**Issue by Breadsniffer** [sensity-ai/dot#47]
The dot_model_checkpoints.zip file seems to be corrupted, when I try to unzip it it gives me 36 unavailable data errors

**Comment by AjinkyaIndulkar** [comment]
Hi @Breadsniffer, please note that due to GitHub's upload size limit, we have created multiple zip files to store the model checkpoints. You will need to download all the zip files before unzipping them.

Please follow the instructions mentioned here: https://github.com/sensity-ai/dot#download-models
