### ISSUE TITLE
Add Colab demo for testing without webcam

### ISSUE THREAD

**Issue by netrunner-exe** [sensity-ai/dot#9]
Please add Colab demo for testing without webcam, thanks!

**Comment by giorgiop** [comment]
This script works without webcam feed: https://github.com/sensity-ai/dot/blob/main/scripts/image_swap.py
You will need access to GPU though, unless you run it on colab yourself

**Comment by giorgiop** [comment]
@hichemfelouat could you give us instructions for reproducing the issue please?

**Comment by hichemfelouat** [comment]
@giorgiop This version has many files that need to extend the PYTHONPATH.

**Comment by hichemfelouat** [comment]
@giorgiop 
The issue is about extending the PYTHONPATH. So for example when we use video_swap.py like this :
!python /content/dot/scripts/video_swap.py \
  -c /content/dot/dot/simswap/configs/config.yaml \
  -s /content/my_img.jpg \
  -t /content/my_video.mp4 \
  -o /content/my_result

The error :
Traceback (most recent call last):
  File "/content/dot/scripts/video_swap.py", line 10, in <module>
    import dot
ModuleNotFoundError: No module named 'dot'

One of the solutions is to add to video_swap.py file
import sys
sys.path.append("/content/dot/dot/")

But unfortunately, approximately all the files need to add to them the two above lines and update their from ... import and import that is too hard when we work on google colab.

**Comment by giorgiop** [comment]
Are you using a conda env? that should solve it

**Comment by AjinkyaIndulkar** [comment]
@hichemfelouat we've added a demo notebook for google colab: https://colab.research.google.com/github/sensity-ai/dot/blob/main/notebooks/colab_demo.ipynb

**Comment by hichemfelouat** [comment]
@AjinkyaIndulkar
Thank you so much I really appreciate that.
